version: '3'
services:
  postgresql:
    image: postgres:12.3
    ports:
      - 5432:5432
    # restart: always
    env_file:
      - postgres.env
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"
    stdin_open: true
    tty: true
  django:
    image: ubuntu_python:latest
    ports:
      - 8000:8000
    volumes:
      - "./:/home/www/projects/avitolog"
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    env_file:
      - postgres.env
      - django.env
    working_dir: /home/www/projects/avitolog
    command: /home/www/projects/avitolog/start_django_service.sh
    #restart: always
    depends_on:
      - postgresql
    links:
      - postgresql
