# Generated by Django 3.0.6 on 2020-06-02 14:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=63, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=63, verbose_name='Мобильный')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('0', 'Краснодар'), ('1', 'Москва')], max_length=2, verbose_name='Город')),
                ('fio', models.CharField(max_length=63, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=63, verbose_name='Мобильный')),
            ],
            options={
                'verbose_name': 'исполнитель',
                'verbose_name_plural': 'исполнители',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime.today, verbose_name='Время создания')),
                ('status', models.CharField(choices=[('0', 'Лид'), ('1', 'Принят'), ('2', 'Назначен'), ('3', 'Выполнен'), ('4', 'Отказ')], max_length=2, verbose_name='Статус')),
                ('comment', models.TextField(max_length=1023, verbose_name='Комментарий')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.Client', verbose_name='Клиент')),
                ('executor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.Executor', verbose_name='Исполнитель')),
                ('rk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rk.Rk')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
    ]
