# Generated by Django 3.0.6 on 2020-06-02 14:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(default='', max_length=2000, verbose_name='Текст')),
                ('image_1', models.ImageField(default='', upload_to='img/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=100)),
                ('create_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
            },
        ),
        migrations.CreateModel(
            name='Rk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Рекламная компания',
                'verbose_name_plural': 'Рекламные компании',
            },
        ),
        migrations.CreateModel(
            name='AdIsUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rk.Ad')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='rk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rk.Rk', verbose_name='Рекламные компании'),
        ),
    ]
