# Generated by Django 3.0.5 on 2020-05-02 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='rk',
            options={'verbose_name_plural': 'Рекламные компании'},
        ),
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ad',
            name='rk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rk.Rk', verbose_name='Рекламные компании'),
        ),
        migrations.CreateModel(
            name='AdIsUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rk.Ad')),
            ],
        ),
    ]
