# Generated by Django 3.0.5 on 2020-05-02 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rk', '0003_auto_20200502_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='create_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
