# Generated by Django 3.0.5 on 2020-05-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rk', '0005_auto_20200502_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'объявление', 'verbose_name_plural': 'объявления'},
        ),
        migrations.AlterModelOptions(
            name='rk',
            options={'verbose_name': 'Рекламная компания', 'verbose_name_plural': 'Рекламные компании'},
        ),
    ]
