# Generated by Django 3.0.5 on 2020-05-02 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(max_length=100)),
                ('create_date', models.DateField(verbose_name='Дата создания')),
                ('rk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rk.Rk', verbose_name='рекламная компания')),
            ],
        ),
    ]
