# Generated by Django 3.0.5 on 2020-05-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rk', '0002_auto_20200502_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image_1',
            field=models.ImageField(default='', upload_to='img/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='ad',
            name='text',
            field=models.TextField(default='', max_length=2000, verbose_name='Текст'),
        ),
    ]
