# Generated by Django 3.0.6 on 2020-06-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('0', 'Ростелеком'), ('1', 'Теле2'), ('2', 'Билайн'), ('3', 'Мегафон'), ('4', 'МТС')], max_length=1, verbose_name='Провайдер')),
                ('tarif', models.CharField(max_length=31, verbose_name='Тариф')),
                ('balans', models.FloatField(verbose_name='Баланс')),
                ('last_balans_check', models.DateField(verbose_name='Дата просмотра баланса')),
                ('last_pay_action', models.DateField(verbose_name='Дата последнего платного действия')),
            ],
            options={
                'verbose_name': 'симка',
                'verbose_name_plural': 'симки',
            },
        ),
    ]
